name: l10n_mapper_generator
description: A dart package to generate localization-mapper to support parsing
  dynamic translation keys (as flutter-localizations package does not yet
  support this).
version: 2.1.7

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  analyzer: ">=7.5.9 <8.0.0"
  args: ^2.4.2
  build: ^3.0.0
  flutter:
    sdk: flutter
  path: ^1.8.3
  source_gen: ^3.0.0
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

executables:
  l10n_mapper_generator: l10n_mapper_generator
